
command /version [<player>]:
   description: Check version of player
   permission: andus.ver
   permission message: &4You don't have permission to that command
   executable by: players and console
   aliases: /ver
   trigger:
       if minecraft version of arg 1 is "1.17":
       	# What server should do with player for ex. teleport him through bungee to survival server
       else:
       	send "&cOnly 1.17 allowed" to player
