
command /wersja [<player>]:
   description: Sprawdz wersje gracza
   permission: andus.ver
   permission message: &4You don't have permission to that command
   executable by: players and console
   aliases: /ver, /version
   trigger:
       if minecraft version of arg 1 is "1.17":
       	# Co serwer powinien zrobiæ z graczem np. teleportuj go przez bungee na serwer survival
       else:
       	send "&cTylko 1.17 dozwolone" to player
